=== RandumbPurson/DMhelper/statblock.json
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"properties": {
		"maxHP": {
			"description": "Maximum hit points",
			"type": "integer"
		},
		"AC": {
			"description": "Armor Class",
			"type": "integer"
		},
        "PB": {
            "description": "Proficiency Bonus",
            "type": "integer"
        },
		"speed":{
			"description": "Various movement speeds",
			"type":"object",
			"properties": {
				"walking": {
					"type": "integer"
				},
				"flying": {
					"type": "integer"
				}
			}
		},
        "stats": {
            "description": "Ability Scores",
            "type": "object",
            "properties": {
                "STR": {"type":"integer"},
                "DEX": {"type":"integer"},
                "CON": {"type":"integer"},
                "INT": {"type":"integer"},
                "WIS": {"type":"integer"},
                "CHA": {"type":"integer"}
            },
            "required": ["STR", "DEX", "CON", "INT", "WIS", "CHA"]
        },
        "actions": {
            "type": "object",
            "description": "Non-attack actions",
            "patternProperties": {
                "^.*$":{
                    "properties": {
                        "text": {"type":"string"},
                        "rolls": {"type":"object"},
                        "uses": {"type": "integer"}
                    }
                }
            },
            "properties": {
                "multiattack":{
                    "type": "array",
                    "description": "A list of attacks given in the format 'x*attack_key' where x is the number of attacks"
                }
            }
        },
        "traits":{
            "type": "object",
            "description": "Additional traits and info"
        },
        "attacks": {
            "type": "object",
            "description": "Basic Attacks",
            "patternProperties": {
                "^.*$":{
                    "patternProperties": {
                        "^type$": {"enum":["melee", "ranged"]}
                    },
                    "properties": {
                        "range": {"type": "string"},
                        "to-hit": {"type": "string"},
                        "damage": {"type": "string"}
                    },
                    "required": ["range", "to-hit", "damage"]
                }
            }
        }
	},
	"required":["maxHP", "AC", "speed", "PB", "stats"]
}

=== RandumbPurson/DMhelper/statblock-examples/common soldier.json
{
	"maxHP": 10,
	"AC": 13,
	"speed": {
		"walking": 30
	},
    "PB": 1,
    "stats": {
        "STR": 12,
        "DEX": 10,
        "CON": 10,
        "INT": 8,
        "WIS": 8,
        "CHA": 8
    },
    "traits": {
        "Unit Fighting": "Roll initiative together, +2 to attack rolls if more than one"
    },
    "attacks": {
        "spear":{
            "type": "melee",
            "range": "20/60",
            "to-hit": "STR + PB",
            "damage": "1d8 + STR, piercing"
        }
    }
}
